mindmap
  root((Hệ Thống pháp luật))



    Supporting["Miền phụ hỗ trợ"]
      Persona["Dịch vụ nhân vật"]
        Select["Chọn nhân vật trò chuyện"]


    Generic["Miền phụ chung"]
      Auth["Dịch vụ Xác thực"]
        Register["Đăng ký tài khoản"]
        Login["Đăng nhập"]
        MFA["Bảo mật 2 lớp 2FA"]
        Profile["Quản lý hồ sơ"]
        Password["Đổi/Quên mật khẩu"]
      Settings["Dịch vụ Cài đặt"]
        Config["Cấu hình cài đặt cá nhân"]
      Payment["Dịch vụ Thanh toán"]
        View_Price["Hiển thị gói VIP & Giá"]
