mindmap
  root((Hệ Thống pháp luật))



    Supporting["Miền phụ hỗ trợ"]
      Persona["Dịch vụ nhân vật"]
        Select["Chọn nhân vật trò chuyện"]


    Generic["Miền phụ chung"]
      Auth["Dịch vụ Xác thực"]
        Register["Đăng ký tài khoản"]
        Login["Đăng nhập"]
      Payment["Dịch vụ Thanh toán"]
        View_Price["Hiển thị gói VIP & Giá"]
